"""
This file was mostly generated by an AI language model (Claude, Anthropic).
Generated code has been reviewed for this project.
"""

import tensorflow as tf
from tensorflow.keras import layers


class GraphConv(layers.Layer):
    """Single graph convolution layer with a fully learnable adjacency matrix.

    Implements the core operation from DGCNN (Song et al., 2018): at each
    call the adjacency matrix ``A_theta`` is normalised via row-wise softmax
    to produce attention-style edge weights, then used to aggregate neighbour
    features before applying a linear projection:

        H = sigma( softmax(A_theta) · X · W + b )

    where ``X ∈ R^{N x F_in}`` is the node feature matrix, ``W ∈ R^{F_in x
    F_out}`` is the trainable weight matrix, and ``A_theta ∈ R^{N x N}`` is
    the fully learnable adjacency matrix. Unlike a fixed distance-based graph,
    ``A_theta`` is updated by backpropagation during training and can discover
    functional connectivity patterns that do not follow physical scalp
    proximity.

    Parameters
    ----------
    units : int
        Output feature dimensionality per node ``F_out``.
    n_nodes : int
        Number of graph nodes N (electrodes). Determines the shape of
        ``A_theta``.
    activation : str or callable, optional
        Activation function applied after the linear transform. Accepts any
        Keras activation identifier or callable. Default is ``"relu"``.
    use_bias : bool, optional
        Whether to add a bias term to the linear transform. Default is
        ``True``.

    Attributes
    ----------
    A_theta : tf.Variable of shape ``(n_nodes, n_nodes)``
        The learnable adjacency matrix, initialised with a Glorot uniform
        distribution and updated during training. Its row-wise softmax is
        used during the forward pass, so raw values are unbounded; the
        softmax enforces that each row sums to 1.
    W : tf.Variable of shape ``(F_in, units)``
        Learnable weight matrix for the node-wise linear projection.
    b : tf.Variable of shape ``(units,)``
        Learnable bias vector. Only created when ``use_bias=True``.

    Notes
    -----
    The forward pass computes ``softmax(A_theta) @ X @ W`` in two dense
    matrix multiplications, which is efficient for small N (e.g. 14
    electrodes). For large graphs this layer does not scale well and sparse
    implementations should be preferred.

    ``A_theta`` is initialised without any structural prior. If domain
    knowledge about electrode topology is available (e.g. inverse scalp
    distances from the 10-20 system), ``A_theta`` can be initialised from
    that matrix via ``layer.A_theta.assign(prior)`` after construction to
    give training a meaningful starting point.

    Examples
    --------
    Applying one graph convolution step to a batch of per-timestep node
    feature matrices:

    >>> gcn = DynamicGraphConvolution(units=32, n_nodes=14)
    >>> x = tf.random.normal((8, 14, 6))   # (batch, nodes, features)
    >>> y = gcn(x)                          # (8, 14, 32)
    """

    def __init__(
        self,
        units: int,
        n_nodes: int,
        activation: str = "relu",
        use_bias: bool = True,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.units = units
        self.n_nodes = n_nodes
        self.use_bias = use_bias
        self.activation = tf.keras.activations.get(activation)

    def build(self, input_shape):
        f_in = input_shape[-1]
        self.A_theta = self.add_weight(
            name="A_theta",
            shape=(self.n_nodes, self.n_nodes),
            initializer="glorot_uniform",
            trainable=True,
        )
        self.W = self.add_weight(
            name="W",
            shape=(f_in, self.units),
            initializer="glorot_uniform",
            trainable=True,
        )
        if self.use_bias:
            self.b = self.add_weight(
                name="b",
                shape=(self.units,),
                initializer="zeros",
                trainable=True,
            )
        super().build(input_shape)

    def call(self, X, training=False):
        """Apply one graph convolution step.

        Parameters
        ----------
        X : tf.Tensor of shape ``(batch, N, F_in)``
            Node feature matrix. ``N`` must equal ``n_nodes``.
        training : bool, optional
            Unused; present for Keras API compatibility.

        Returns
        -------
        tf.Tensor of shape ``(batch, N, units)``
            Updated node embeddings after neighbourhood aggregation and
            linear projection.
        """
        A_norm = tf.nn.softmax(self.A_theta, axis=-1)  # (N, N)
        AX = tf.matmul(A_norm, X)  # (batch, N, F_in)
        H = tf.matmul(AX, self.W)  # (batch, N, units)
        if self.use_bias:
            H = H + self.b
        return self.activation(H)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "units": self.units,
                "n_nodes": self.n_nodes,
                "activation": tf.keras.activations.serialize(self.activation),
                "use_bias": self.use_bias,
            }
        )
        return config